### ISSUE TITLE
Error in Star rating and Show Image 

### ISSUE THREAD

**Issue by ippatel** [ravikumar4/p-product#2]
Hi,
 I was trying to add Stars for Star rating but when I imported "@import "~font-awesome/css/font-awesome.min.css" which I saw in the video I got error. Also, I did something because of which my images of item (which were displaying before) are now not visible. Please help me find solution.

![Screenshot (20)](https://user-images.githubusercontent.com/52467075/61908876-ac784480-aefe-11e9-8f1e-0dd7d4a5b81c.png)

**Comment by ravikumar4** [comment]
Following need to be done to use font-awesome:
1. npm install font-awesome
2. update style.css/style.scss file with the import as mentioned here
https://fontawesome.com/v4.7.0/get-started/
.
